name: Cache Prime Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-dependencies
          key: cache-43b8a0b

      - name: prime-cache-43b8a0b
        run: echo "Cache hit: ${{ steps.cache-deps.outputs.cache-hit }}"
